name: test-workflow
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello World!"
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - name: Print goodbye
        run: echo "Good Bye!"
